apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cloudflare-ddns
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cloudflare-ddns
              image: mirioeggmann/cloudflare-ddns:latest
              env:
              - name: ZONE_ID
                value: ""
              - name: RECORD_ID
                value: ""
              - name: AUTH_KEY
                value: ""
              - name: AUTH_EMAIL
                value: ""
              - name: NAME
                value: ""
          restartPolicy: OnFailure
